---
---
title: "R Notebook"
author: Katia Pechenkina
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Turn off scientific notation
options(scipen=999)
library(tidyverse)
library(readxl)
library(lubridate)
library(dplyr)

```


```{r}

write_csv(military_presence_data, "military_presence.csv")
```
QUESTION #1:What are the biggest shifts in the locations of military personnel between 2008-2016, either into or out of a country?

###I was not sure that the date and year columns were in correct format so I looked using glimpse function. 
```{r}
 glimpse(military_presence_data)
```

```{r}
###This might be a lot of data sets but it's clean and I can see 2008 and 2016 for each of the Active duty categories. 

obama_08_and_16 <- military_presence_data%>% 
filter(year=="2008")
```

```{r}
Obama_08_Army_Active_Duty <- military_presence_data %>%
filter(Year == "2008")%>%
group_by(Location,Army_Active_Duty,Year)%>%
  summarise()%>%
arrange(desc(Army_Active_Duty))

Obama_08_Navy_Active_Duty <- military_presence_data %>%
filter(Year == "2008")%>%
group_by(Location,Navy_Active_Duty,Year)%>%
  summarise()%>%
arrange(desc(Navy_Active_Duty))

Obama_08_Marine_Corps_Active_Duty <- military_presence_data %>%
filter(Year == "2008")%>%
group_by(Location,Marine_Corps_Active_Duty,Year)%>%
  summarise()%>%
arrange(desc(Marine_Corps_Active_Duty))

Obama_08_Air_Force_Active_Duty<- military_presence_data %>%
filter(Year == "2008")%>%
group_by(Location,Air_Force_Active_Duty,Year)%>%
  summarise()%>%
arrange(desc(Air_Force_Active_Duty))

Obama_08_Coast_Guard_Active_Duty<- military_presence_data %>%
filter(Year == "2008")%>%
group_by(Location,Coast_Guard_Active_Duty,Year)%>%
  summarise()%>%
arrange(desc(Coast_Guard_Active_Duty))

```

```{r}

Obama_16_Army_Active_Duty <- military_presence_data %>%
filter(Year == "2016")%>%
group_by(Location,Army_Active_Duty,Year)%>%
  summarise()%>%
arrange(desc(Army_Active_Duty))%>%
rename(Army_Active_Duty_16 = Army_Active_Duty)

Obama_16_Navy_Active_Duty <- military_presence_data %>%
filter(Year == "2016")%>%
group_by(Location,Navy_Active_Duty,Year)%>%
  summarise()%>%
arrange(desc(Navy_Active_Duty))%>%
rename(Navy_Active_Duty_16 = Navy_Active_Duty)


Obama_16_Marine_Corps_Active_Duty <- military_presence_data %>%
filter(Year == "2016")%>%
group_by(Location,Marine_Corps_Active_Duty,Year)%>%
  summarise()%>%
arrange(desc(Marine_Corps_Active_Duty))%>%
rename(Marine_Corps_Active_Duty_16 = Marine_Corps_Active_Duty)


Obama_16_Air_Force_Active_Duty<- military_presence_data %>%
filter(Year == "2016")%>%
group_by(Location,Air_Force_Active_Duty,Year)%>%
  summarise()%>%
arrange(desc(Air_Force_Active_Duty))%>%
rename(Air_Force_Active_Duty_16 = Air_Force_Active_Duty)

Obama_16_Coast_Guard_Active_Duty<- military_presence_data %>%
filter(Year == "2016")%>%
group_by(Location,Coast_Guard_Active_Duty,Year)%>%
  summarise()%>%
arrange(desc(Coast_Guard_Active_Duty))%>%
rename(Coast_Guard_Active_Duty_16 = Coast_Guard_Active_Duty)

```
```{r}

obama_08_and_16 <- military_presence_data %>%
  filter(Year == "2008" | Year == "2016")%>%
group_by(Location,Army_Active_Duty,Navy_Active_Duty,Marine_Corps_Active_Duty,Air_Force_Active_Duty,Coast_Guard_Active_Duty,Year)
 
military_total_08 <- obama_08_and_16 %>% 
  filter(Year == "2008")%>%
  group_by(Location, Year = 2008) %>% 
  summarize(
    total_army = sum(Army_Active_Duty),
    total_navy = sum(Navy_Active_Duty),
    total_marine_corps = sum(Marine_Corps_Active_Duty),
    total_air_force = sum(Air_Force_Active_Duty),
    total_coast_guard = sum(Coast_Guard_Active_Duty),
   total_08 = total_army + total_navy + total_marine_corps + total_air_force + total_coast_guard
  )  

  
military_total_16 <- obama_08_and_16 %>% 
  filter(Year == "2016")%>%
  group_by(Location, Year = 2016) %>% 
  summarize(
    total_army = sum(Army_Active_Duty),
    total_navy = sum(Navy_Active_Duty),
    total_marine_corps = sum(Marine_Corps_Active_Duty),
    total_air_force = sum(Air_Force_Active_Duty),
    total_coast_guard = sum(Coast_Guard_Active_Duty),
    total_16 = total_army + total_navy + total_marine_corps + total_air_force + total_coast_guard
  ) 



military_08 <- military_total_08%>%
mutate(delta = total_08 - lag(total_08))%>%
   select(-total_08) 


military_total_08 %>%left_join (military_total_16)

```
